# Generated by Django 2.1.4 on 2019-03-05 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('professor', 'professor'), ('student', 'student')], default='professor', max_length=9)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10, null=True, unique=True)),
                ('mobile', models.CharField(max_length=10, null=True, unique=True)),
                ('address', models.CharField(max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('student', 'student')], default='student', max_length=7)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15, unique=True)),
                ('total_marks', models.IntegerField()),
                ('total_classes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I', models.IntegerField(blank=True, null=True)),
                ('II', models.IntegerField(blank=True, null=True)),
                ('III', models.IntegerField(blank=True, null=True)),
                ('attendence', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.SemesterSub')),
            ],
        ),
        migrations.AddField(
            model_name='semestersub',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.Subject'),
        ),
    ]
