# Generated by Django 2.1.4 on 2019-03-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_professorsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorsub',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professorsub',
            name='subject',
        ),
        migrations.AddField(
            model_name='semestersub',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
        ),
        migrations.DeleteModel(
            name='ProfessorSub',
        ),
    ]
