# Generated by Django 2.1.4 on 2019-03-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20190305_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersub',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
        ),
    ]
