# Generated by Django 2.1.4 on 2019-03-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_semestersub_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='status',
            field=models.CharField(choices=[('professor', 'professor'), ('student', 'student')], default='professor', max_length=9),
        ),
        migrations.AlterField(
            model_name='semestersub',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
        ),
    ]
