# Generated by Django 2.1.4 on 2019-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20190306_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='total_classes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submarks',
            name='I',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submarks',
            name='II',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submarks',
            name='III',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submarks',
            name='attendence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
