# Generated by Django 2.1.4 on 2019-03-07 09:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0007_auto_20190306_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('assignment', models.FileField(upload_to='assignments/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(3, 3), (5, 5), (6, 6), (10, 10), (4, 4), (7, 7), (9, 9), (8, 8), (2, 2), (1, 1)], default=1, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignments',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Professor'),
        ),
    ]
