# Generated by Django 2.1.4 on 2019-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20190307_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (9, '9'), (6, '6'), (10, '10'), (4, '4'), (7, '7'), (8, '8'), (3, '3'), (2, '2'), (5, '5')], default=1, max_length=1),
        ),
    ]
