# Generated by Django 2.1.4 on 2019-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20190307_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', 5), ('4', 4), ('3', 3), ('1', 1), ('9', 9), ('10', 10), ('2', 2), ('7', 7), ('8', 8), ('6', 6)], default=1, max_length=1),
        ),
    ]
