# Generated by Django 2.1.4 on 2019-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20190307_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(3, 3), (5, 5), (6, 6), (10, 10), (4, 4), (7, 7), (9, 9), (8, 8), (2, 2), (1, 1)], default=1),
        ),
    ]
