# Generated by Django 2.1.4 on 2019-03-14 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_auto_20190307_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
