# Generated by Django 2.1.4 on 2019-03-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_assignments_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
