# Generated by Django 2.1.4 on 2019-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_auto_20190314_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
