# Generated by Django 2.1.4 on 2019-03-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20190319_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.TextField(max_length=14),
        ),
    ]
