# Generated by Django 2.1.4 on 2019-03-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
    ]
