# Generated by Django 2.1.4 on 2019-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_remove_review_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
