# Generated by Django 2.1.4 on 2019-03-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_auto_20190324_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BatchAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.BatchAdd'),
        ),
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Student'),
        ),
    ]
