# Generated by Django 2.1.4 on 2019-03-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0027_auto_20190325_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
