# Generated by Django 2.1.4 on 2019-03-29 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0034_auto_20190326_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
